### ISSUE TITLE
Cannot import name 'CropRandomizer' from 'robomimic.models.base_nets'

### ISSUE THREAD

**Issue by BaymaxShao** [UT-Austin-RPL/VIOLA#4]
I try training the model with your generated datasets, and get this error:
**Cannot import name 'CropRandomizer' from 'robomimic.models.base_nets'**

With suspecting incorrect installation of _robomimic_, I go to https://github.com/ARISE-Initiative/robomimic/blob/master/robomimic/models/base_nets.py to check. However, I can't find CropRandomizer and Randomizer either.

Could you help me figure out why and how?

**Comment by zhuyifengzju** [comment]
Hi, it could be that they've updated their codebase. Please modify the code accordingly to accommodate their new changes, or you will need to install an older version of robomimic to use these classes.

**Comment by ramkumarkoppu** [comment]
having pip installation from requirements.txt file. what is the python version proven to be working for this repo?

**Comment by HeegerGao** [comment]
Encounter the same issue in another project. Upgrading the robomimic version to 0.3.0 solves this problem. 

`pip install robomimic==0.3.0`

**Comment by sanikanandpure** [comment]
> Encounter the same issue in another project. Upgrading the robomimic version to 0.3.0 solves this problem.
> 
> `pip install robomimic==0.3.0`

Still encountering the same issue even after upgrading to 0.3.0.
